-- 1. 계열 정보를 저장할 카테고리 테이블 작성
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2. 과목 구분을 저장할 테이블 작성
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5),
    NAME VARCHAR2(10),
    CONSTRAINT PK_TCT_NO PRIMARY KEY(NO)
);

-- 3. TB_CATEGORY테이블의 NAME컬럼에 PRIMARY KEY 생성
ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_TC_NAME PRIMARY KEY(NAME);

-- 4. TB_CLASS_TYPE테이블의 NAME컬럼에 NULL값이 들어가지 않도록 속성 변경
ALTER TABLE TB_CLASS_TYPE MODIFY NAME CONSTRAINT NN_TCT_NAME NOT NULL;

-- 5. 두 테이블에서 컬럼명이 NO인 것은 기존 타입을 유지하면서 크기는 10으로,
--    컬럼명이 NAME인 것은 기존 타입 유지하면서 크기 20으로 변경
ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

-- 6. 두 테이블의 NO컬럼과 NAME컬럼의 이름을 각각 TB_를 제외한 테이블 이름이 앞에 붙은 형태로 변경(EX. CATEGORY_NAME)
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_NO;
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASSTYPE_NAME;

ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

-- 7. TB_CATEGORY테이블과 TB_CLASS_TYPE테이블의 PRIMARY KEY 이름을 다음과 같이 변경
--    PRIMARY KEY의 이름을 "PK_ + 컬럼이름"으로 지정 (EX. PK_CATEGORY_NAME)
ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT PK_TC_NAME TO PK_CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT PK_TCT_NO TO PK_CLASS_NO;

-- 8. 
INSERT INTO TB_CATEGORY VALUES('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회', 'Y');
COMMIT;

-- 9. TB_DEPARTMENT의 CATEGORY컬럼이 TB_CATEGORY테이블의 CATEGORY_NAME컬럼을 부모 값으로 참조하도록 FOREIGN KEY 지정
--    KEY 이름은 FK_테이블이름_컬럼이름으로 지정 (EX. FK_DEPARTMENT_CATEGORY)
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) 
REFERENCES TB_CATEGORY(CATEGORY_NAME);

-- 10~14. VIEW 관련 생략

-- 15. 최근 3년 기준 수강인원이 가장 많았던 3과목 출력
SELECT *
FROM (SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름, COUNT(CLASS_NO) "누적 수강생수"
      FROM TB_CLASS
           JOIN TB_GRADE USING(CLASS_NO)
      WHERE SUBSTR(TERM_NO, 1, 4) >= 2007 -- 2005로 하면 예시와 같이 나옴
      GROUP BY CLASS_NO, CLASS_NAME
      ORDER BY 3 DESC)
WHERE ROWNUM <= 3;