CREATE TABLE `Student` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled2` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled3` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled4` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled5` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Key2`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `Untitled6` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field3`	VARCHAR(255)	NULL
);

CREATE TABLE `고객` (
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key`	VARCHAR(255)	NOT NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled7` (
	`Field`	VARCHAR(255)	NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Key`	VARCHAR(255)	NOT NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Key2`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `Untitled8` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled9` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

ALTER TABLE `Student` ADD CONSTRAINT `PK_STUDENT` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled` ADD CONSTRAINT `PK_UNTITLED` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled2` ADD CONSTRAINT `PK_UNTITLED2` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled3` ADD CONSTRAINT `PK_UNTITLED3` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled4` ADD CONSTRAINT `PK_UNTITLED4` PRIMARY KEY (
	`Key`,
	`Key2`
);

ALTER TABLE `Untitled5` ADD CONSTRAINT `PK_UNTITLED5` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled6` ADD CONSTRAINT `PK_UNTITLED6` PRIMARY KEY (
	`Key`
);

ALTER TABLE `고객` ADD CONSTRAINT `PK_고객` PRIMARY KEY (
	`Key2`
);

ALTER TABLE `Untitled7` ADD CONSTRAINT `PK_UNTITLED7` PRIMARY KEY (
	`Field`,
	`Key3`
);

ALTER TABLE `Untitled8` ADD CONSTRAINT `PK_UNTITLED8` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled9` ADD CONSTRAINT `PK_UNTITLED9` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled4` ADD CONSTRAINT `FK_Untitled3_TO_Untitled4_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled3` (
	`Key`
);

ALTER TABLE `Untitled6` ADD CONSTRAINT `FK_Untitled5_TO_Untitled6_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled5` (
	`Key`
);

ALTER TABLE `Untitled7` ADD CONSTRAINT `FK_Untitled9_TO_Untitled7_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled9` (
	`Key`
);

