BEGIN
    FOR I IN 1..97
    LOOP
        INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, 10, I, 100 + I, 'admin', DEFAULT, SYSDATE, SYSDATE, DEFAULT);
    END LOOP;
END;
/

COMMIT;

SELECT *
FROM(SELECT ROWNUM RNUM, DESCBOARD.*
    FROM(SELECT BOARD_ID, BOARD_TYPE, CATE_NAME, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, NICKNAME, BOARD_COUNT, CREATE_DATE, B.MODIFY_DATE, B.STATUS
         FROM BOARD B
              JOIN CATEGORY C USING(CATE_ID)
              JOIN MEMBER M ON(USER_ID = BOARD_WRITER)
         WHERE B.STATUS = 'Y' 
               AND BOARD_TYPE = 1
         ORDER BY BOARD_ID DESC) DESCBOARD) -- 별칭 지정
WHERE RNUM >= 11 AND RNUM <= 20;
-- 동작은 하지만 비효율적

CREATE OR REPLACE VIEW BLIST
AS
SELECT ROWNUM RNUM, DESCBOARD.*
FROM(SELECT BOARD_ID, BOARD_TYPE, CATE_NAME, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, 
            NICKNAME, BOARD_COUNT, CREATE_DATE, B.MODIFY_DATE, B.STATUS
     FROM BOARD B
          JOIN CATEGORY C USING(CATE_ID)
          JOIN MEMBER M ON(USER_ID = BOARD_WRITER)
     WHERE B.STATUS = 'Y' 
           AND BOARD_TYPE = 1
     ORDER BY BOARD_ID DESC) DESCBOARD;
-- 권한이 불충분합니다 -> 관리자 계정으로 권한 부여해야 함

GRANT CREATE VIEW TO JSP_Servlet;

SELECT * FROM BLIST
WHERE RNUM >= 11 AND RNUM <= 20;
-- 훨씬 간편해짐
